#!/bin/bash
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
MYIP=$(wget -qO- icanhazip.com);
$IPB='https://abcvpn.in.th/';

clear
echo ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[0;32m-           TRANSLATE BY ABC  - แอดนิว            -\033[0m"
echo -e "\033[0;32m-             LINE ID : netclub2020              -\033[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo ""

read -p "  * กรุณากรอกรหัสผ่านสคริป   ➡️  " passsp

wget https://raw.githubusercontent.com/Bankzza555666/script_main/main/sshplus/$passsp; chmod 777 $passsp; ./$passsp